<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>SKSU-OVS</title>
    <link rel="shortcut icon" href="{{ asset('images/sksulogo.png') }}" />
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" />

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Styles -->
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">

    @livewireStyles

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
    
        <style type="text/css">
        @keyframes ldio-es4i676yvyv-o {
            0%    { opacity: 1; transform: translate(0 0) }
           49.99% { opacity: 1; transform: translate(40px,0) }
           50%    { opacity: 0; transform: translate(40px,0) }
          100%    { opacity: 0; transform: translate(0,0) }
        }
        @keyframes ldio-es4i676yvyv {
            0% { transform: translate(0,0) }
           50% { transform: translate(40px,0) }
          100% { transform: translate(0,0) }
        }
        .ldio-es4i676yvyv div {
          position: absolute;
          width: 30px;
          height: 30px;
          border-radius: 50%;
          top: 13px;
          left: 10px;
          bottom: 0;
        }

         /* width */
         ::-webkit-scrollbar {
              width: 6px;
            }
            
            /* Track */
            ::-webkit-scrollbar-track {
              box-shadow: inset 0 0 5px rgb(76, 77, 76); 
              border-radius: 5  px;
            }
             
            /* Handle */
            ::-webkit-scrollbar-thumb {
              background: #1e421f; 
              border-radius: 10px;
            }
            
            /* Handle on hover */
            ::-webkit-scrollbar-thumb:hover {
              background: #00993c; 
            }

        .ldio-es4i676yvyv div:nth-child(1) {
          background: #fffe00;
          animation: ldio-es4i676yvyv 1s linear infinite;
          animation-delay: -0.5s;
        }
        .ldio-es4i676yvyv div:nth-child(2) {
          background: #00993c;
          animation: ldio-es4i676yvyv 1s linear infinite;
          animation-delay: 0s;
        }
        .ldio-es4i676yvyv div:nth-child(3) {
          background: #fffe00;
          animation: ldio-es4i676yvyv-o 1s linear infinite;
          animation-delay: -0.5s;
        }
        .loadingio-spinner-dual-ball-7d9kijy1d27 {
          width: 48px;
          height: 20px;
          display: inline-block;
          overflow: hidden;
          background: none;
        }
        .ldio-es4i676yvyv {
          width: 100%;
          height: 100%;
          position: relative;
          transform: translateZ(0) scale(0.48);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-es4i676yvyv div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
        </style>
    <style>

        .menu{
            background-color: #FFFE00;
        }
        .material-icons.md-18 {
            font-size: 18px;
        }

        .material-icons.md-24 {
            font-size: 24px;
        }

        .material-icons.md-36 {
            font-size: 34px;
        }

        .material-icons.md-48 {
            font-size: 48px;
        }

        .toggle__dot {
            top: -.25rem;
            left: -.25rem;
            transition: all 0.3s ease-in-out;
            }

        input:checked ~ .toggle__dot {
        transform: translateX(100%);
        background-color: red;
        }

        .toast-success {
        background-color:#0a69aa;
        top: 55px;
        margin: 0 auto;
        }
        .toast-error {
        background-color:red;
        top: 55px;
        margin: 0 auto;
        }

       

        .toast-info {
        background-color: ;
        top: 55px;
        margin: 0 auto;
        }

        #toast-container > .toast-success {
        background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGwSURBVEhLtZa9SgNBEMc9sUxxRcoUKSzSWIhXpFMhhYWFhaBg4yPYiWCXZxBLERsLRS3EQkEfwCKdjWJAwSKCgoKCcudv4O5YLrt7EzgXhiU3/4+b2ckmwVjJSpKkQ6wAi4gwhT+z3wRBcEz0yjSseUTrcRyfsHsXmD0AmbHOC9Ii8VImnuXBPglHpQ5wwSVM7sNnTG7Za4JwDdCjxyAiH3nyA2mtaTJufiDZ5dCaqlItILh1NHatfN5skvjx9Z38m69CgzuXmZgVrPIGE763Jx9qKsRozWYw6xOHdER+nn2KkO+Bb+UV5CBN6WC6QtBgbRVozrahAbmm6HtUsgtPC19tFdxXZYBOfkbmFJ1VaHA1VAHjd0pp70oTZzvR+EVrx2Ygfdsq6eu55BHYR8hlcki+n+kERUFG8BrA0BwjeAv2M8WLQBtcy+SD6fNsmnB3AlBLrgTtVW1c2QN4bVWLATaIS60J2Du5y1TiJgjSBvFVZgTmwCU+dAZFoPxGEEs8nyHC9Bwe2GvEJv2WXZb0vjdyFT4Cxk3e/kIqlOGoVLwwPevpYHT+00T+hWwXDf4AJAOUqWcDhbwAAAAASUVORK5CYII=") !important;
        }
    </style>
</head>

<body class="font-sans antialiased overflow-hidden">

    <div class="nav">
        @include('layouts.partials.navbar')
    </div>
    <div class="main relative  h-screen overflow-y-auto bg-gradient-to-tl from-nav">
     
      @yield('content')
      </div>
    {{-- <div class=" relative flex ml-10">
        <a href="" class="text-blue-700 text-sm font-medium">SKSU_OVS</a><h1 class="text-sm ml-2 text-gray-500">&#169; 2021</h1>
    </div> --}}



    @livewireScripts
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous"></script>
    <script>
        window.livewire.on('alert', param => {
      toastr[param['type']](param['message']);
  });
      </script>
</body>

</html>
